apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  selector:
    app: {{APP_NAME}}
  ports:
    - name: queue-port
      port: 5672
    - name: management-port
      port: 15672
    - name: cluster-port
      port: 4369
    - name: dist-port
      port: 25672
